blast_db_dir: "/Users/sofiarouot/Documents/SnakeMake/part2_cross-hyb/db"
blast_dbs:
  - "env_nt"
  - "nt_prok"
  - "nt_viruses"
num_probe_pairs: 3  # Number of probe pairs to include for each sequence ID
